# ~/.config/starship.toml

# Donâ€™t print an extra blank line before the prompt
add_newline = false

# Compact, single-line prompt ïŒ’ ğŸ§ 
format = """
[î‚¶](bg:#030B16ff fg:#7DF9AA)\
[ïŒ’ ](bg:#7DF9AA fg:#090c0c)\
[î‚°](fg:#7DF9AA bg:#1C3A5E)\
$time\
$username\
$hostname\
[î‚°](bg:#3B76F0 fg:#1C3A5E)\
$directory\
$git_branch\
$git_state\
$git_status\
$python\
$cmd_duration\
$status\
[î‚°](fg:#3B76F0 bg:#030B16ff)\
$character
"""

[username]
show_always = true
style_user = "bg:1d2230"
format = "[[ $user ](bg:#1C3A5E fg:#8DFBD2)]($style_user)"

[hostname]
ssh_only = true
style = "bg:1d2230"
format = "[[ â›‰ $hostname ](bg:#1C3A5E fg:#8DFBD2)]($style)"

[directory]
truncation_length = 0
truncate_to_repo = false
home_symbol = "~"
format = "[ $path ]($style)"
style = "fg:#E4E4E4 bg:#3B76F0"

[git_branch]
symbol = "îœ‰ ï˜ "
style = "fg:#1C3A5E bg:#FCF392"
format = "[$symbol$branch]($style) "

[git_metrics]
format = "([+$added]($added_style))[]($added_style)"
added_style = "fg:#1C3A5E bg:#FCF392"
deleted_style = "fg:bright-red bg:235"
disabled = false

[git_state]
format = '[\($state( $count)\)](yellow) '

[git_status]
format = '\[$all_status$ahead_behind\] '
style = "fg:#1C3A5E bg:#FCF392"
ahead    = 'â‡¡${count}'
behind   = 'â‡£${count}'
diverged = 'â‡•${ahead_count}/${behind_count}'

[cmd_duration]
min_time = 2_000
format = "[$duration]($style)"
style = "fg:#FFFFFF bg:#3B76F0 "

#[status]
#format = '[$symbol]($style) '
#symbol         = "[âœ˜](red) "
#success_symbol = "[âœ”](green) "
#style          = "bold red"
#success_style  = "bold green"
#disabled       = false
#recognize_signal_code = true
#map_symbol            = false

[character]
success_symbol = '[ âœ](bold green) '
error_symbol = '[ âœ—](#E84D44) '

[python]
symbol = "ğŸ "
pyenv_version_name = true
format = 'venv [${symbol}${version}(\($virtualenv\))]($style) '

[time]
disabled = false
time_format = "ó±‘ %R %m/%d/%y" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[ $time ](bg:#1C3A5E fg:#8DFBD2)]($style)'
